import { aws_lambda as Lambda, aws_dynamodb } from 'aws-cdk-lib';
import { IRole } from 'aws-cdk-lib/aws-iam';
import { FilterPattern, IFilterPattern, RetentionDays, SubscriptionFilter } from 'aws-cdk-lib/aws-logs';
import { LambdaDestination } from 'aws-cdk-lib/aws-logs-destinations';
import { Construct } from 'constructs';
import { LambdaReadOnlyPolicy } from './iam/lambda-readonly-policy';

type T = Lambda.Function;

export interface ApiFunctionProps {
  description: string;
  codePath: string;
  table: aws_dynamodb.ITable;
  tablePermissions: string;
  applicationUrlBase?: string;
  environment?: {[key: string]: string};
  monitoredBy?: Lambda.IFunction;
  monitorFilterPattern?: IFilterPattern;
  readOnlyRole: IRole;
  apiFunction: {new(scope: Construct, id:string, props?: Lambda.FunctionProps): T };
}

export class ApiFunction extends Construct {
  lambda: Lambda.Function;
  constructor(scope: Construct, id: string, props: ApiFunctionProps) {
    super(scope, id);
    // See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsx86-64.html
    const insightsArn = 'arn:aws:lambda:eu-west-1:580247275435:layer:LambdaInsightsExtension:16';
    this.lambda = new props.apiFunction(this, 'lambda', {
      runtime: Lambda.Runtime.NODEJS_18_X,
      handler: 'index.handler',
      description: props.description,
      memorySize: 512,
      logRetention: RetentionDays.ONE_MONTH,
      code: Lambda.Code.fromInline('empty'),
      insightsVersion: Lambda.LambdaInsightsVersion.fromInsightVersionArn(insightsArn),
      environment: {
        SESSION_TABLE: props.table.tableName,
        ...props.environment,
      },
    });
    props.table.grantReadWriteData(this.lambda.grantPrincipal);

    if (props.monitoredBy) {
      this.monitor(props.monitoredBy, props.monitorFilterPattern);
    }
    this.allowAccessToReadOnlyRole(props.readOnlyRole);
  }

  /**
   * Monitor the logs generated by this function for a filter pattern, send
   * to specified lambda.
   *
   * @param monitoredBy Lambda function responsible for monitoring this function
   * @param filterPattern Pattern to filter by (default: containing ERROR)
   */
  private monitor(monitoredBy: Lambda.IFunction, filterPattern?: IFilterPattern) {
    new SubscriptionFilter(this, 'error-logs-subscription', {
      logGroup: this.lambda.logGroup,
      destination: new LambdaDestination(monitoredBy),
      filterPattern: filterPattern ?? FilterPattern.anyTerm('ERROR'),
    });
  }

  private allowAccessToReadOnlyRole(role: IRole) {
    role.addManagedPolicy(
      new LambdaReadOnlyPolicy(this, 'read-policy', {
        functionArn: this.lambda.functionArn,
        logGroupArn: this.lambda.logGroup.logGroupArn,
      }),
    );
  }
}
